services:
  - type: web
    name: enfue-search-demo
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
      - key: TYPESENSE_HOST
        value: localhost
      - key: TYPESENSE_API_KEY
        value: Hu52dwsas2AdxdE
    healthCheckPath: /health
    autoDeploy: true
